
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/pages/index
	@mkdir  ../../sea-modules/pages/index
	@mkdir  ../../sea-modules/pages/index/1.0.0
	@cp     dist/*.* ../../sea-modules/pages/index/1.0.0
	@echo
	@echo   " deploy to seajs-modules/pages/index/1.0.0"
	@echo
